---
- block:

    - name: Create ACCESS directory
      file:
        path: ~/access
        state: directory
        owner: access

    - name: Copy docker-compose.yml
      copy:
        src: ../files/docker-compose.yml
        dest: ~/access/docker-compose.yml
        mode: 0700

    - name: Create .env file
      template:
        src: ../files/env.j2
        dest: ~/access/.env
        mode: 0700

    - name: Create empty folders
      file:
        path: "{{ item.name }}"
        state: directory
      with_items:
        - { name: '~/access/backend-config' }
        - { name: '~/access/logs' }
        - { name: '~/access/volumes/mongodb' }
        - { name: '~/access/volumes/postgres' }
        - { name: '~/access/nginx/ssl' }
        - { name: '~/access/nginx/letsencrypt' }
        - { name: '~/access/certs-docker' }
        - { name: '~/access/.ssh' }

    - name: Create backend configs folder
      file:
        path: ~/access/backend-config
        state: directory

    - name: Create repositories.json file
      copy:
        src: host_files/{{ inventory_hostname }}/repositories.json
        dest: ~/access/backend-config/repositories.json
        mode: 0700

    - name: Copy keycloak ACCESS themes folder
      unarchive:
        src: ../files/keycloak-themes.zip
        dest: ~/access/

    - name: Copy nginx conf
      template:
        src: "host_files/{{ inventory_hostname }}/conf-no-tls.nginx.j2
        dest: ~/access/nginx/conf.nginx
        mode: 600

    - name: Use letsencrypt?
      debug:
        msg: "{{ 'Using letsencrypt' if letsencrypt else 'Running web server on port 80' }}"

    - name: Create frontend ssl key pair
      shell: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ~/access/nginx/ssl/server.key -out ~/access/nginx/ssl/server.crt -subj "/C=CH/ST=Zuerich/L=Zuerich/O=ACCESS/OU=ACCESS/CN={{ ansible_ssh_host }}" -addext "subjectAltName = IP:{{ ansible_ssh_host }},DNS:{{ inventory_hostname }}"
      when: not letsencrypt

    - name: Copy selfsigned nginx conf
      copy:
        src: "host_files/{{ inventory_hostname }}/conf-selfsigned.nginx"
        dest: ~/access/nginx/conf.nginx
        mode: 600
      when: not letsencrypt

    - name: Copy docker certs for client
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: 0700
      with_items:
        - { src: 'host_files/{{ inventory_hostname }}/ca.pem', dest: '~/access/certs-docker/ca.pem' }
        - { src: 'host_files/{{ inventory_hostname }}/client-cert.pem', dest: '~/access/certs-docker/cert.pem' }
        - { src: 'host_files/{{ inventory_hostname }}/client-key.pem', dest: '~/access/certs-docker/key.pem' }

    - name: Copy git ssh keys
      copy:
        src: "host_files/{{ inventory_hostname }}/git/"
        dest: "~/access/.ssh"

    - name: Copy ssh config
      copy:
        src: "host_files/{{ inventory_hostname }}/ssh_config"
        dest: ~/access/.ssh/config
        mode: 0700

    - name: Start keycloak and postgres
      docker_compose:
        project_src: ~/access
        files: docker-compose.yml
        services:
          - postgres
          - keycloak

    - name: Wait on keycloak
      pause:
        seconds: 30

    - name: Copy realm provisioning script
      copy:
        src: ../files/access-realm-config.sh
        dest: ~/access/access-realm-config.sh
        mode: 0555

    - name: Add and configure realm
      block:
        - shell: |
            docker cp ~/access/access-realm-config.sh $(docker-compose -f ~/access/docker-compose.yml ps -q keycloak):/opt/jboss/keycloak
            docker-compose -f ~/access/docker-compose.yml exec keycloak bash -c "sh /opt/jboss/keycloak/access-realm-config.sh"
          register: error
      rescue:
        - debug:
            msg: "Keycloak: {{ 'realm already exists' if 'Conflict detected' in error.stdout else 'Something unexpected happened' }}"

    - name: Start ACCESS
      docker_compose:
        project_src: ~/access
        files: docker-compose.yml

- block:
    - name: Copy and unarchive letsencrypt directory
      unarchive:
        src: host_files/{{ inventory_hostname }}/letsencrypt.tgz
        dest: ~/access/nginx
      register: unarchive_letsencrypt
  rescue:
    - debug:
        msg: "Failed to copy and extract old certificates"
    - debug: var=unarchive_letsencrypt.msg
      when: unarchive_letsencrypt is defined
  tags:
    - upload-letsencrypt

- block:
    - name: Get lets encrypt cert
      shell:
        cmd: "docker-compose exec frontend certbot --nginx --register-unsafely-without-email --agree-tos --non-interactive --keep-until-expiring -d {{ web_server_name }}"
        chdir: ~/access
      register: letsencrypt_out
      when: letsencrypt
    - name: Letsencrypt out
      debug: var=letsencrypt_out

    - name: Compress letsencrypt directory
      archive:
        path: ~/access/nginx/letsencrypt
        dest: ~/access/letsencrypt.tgz
      when: letsencrypt

    - name: Copy certs to repo to avoid incurring into rate limiter
      fetch:
        src: ~/access/letsencrypt.tgz
        dest: host_files/{{ inventory_hostname }}/letsencrypt.tgz
        flat: yes
      when: letsencrypt

  tags:
    - letsencrypt
