version: '3.9'

services:
  postgres:
      image: postgres:14.1-alpine
      volumes:
        - postgresdata:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  mongo:
      image: mongo:5.0.5
      container_name: mongo
      environment:
        TZ: Europe/Zurich
      ports:
        - "27017:27017"
      volumes:
        - mongodata:/data/db
  mailhog:
      image: mailhog/mailhog
      hostname: mailhog
      entrypoint: "MailHog -invite-jim -jim-linkspeed-affect=1 -jim-linkspeed-max=1 -jim-linkspeed-min=1"
      ports:
        - "1025:1025"
        - "8025:8025"
  keycloak:
      image: jboss/keycloak:16.1.0
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        TZ: Europe/Zurich
      ports:
        - "9999:8080"
      depends_on:
        - postgres
      command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=singleFile"
      - "-Dkeycloak.migration.file=/opt/jboss/keycloak/realm-config.json"
      - "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
      volumes:
        - ./keycloak-configs/keycloak-export.json:/opt/jboss/keycloak/realm-config.json
        - ./keycloak-themes/access:/opt/jboss/keycloak/themes/access
volumes:
  mongodata:
  postgresdata:
