- hosts: worker
  become: yes
  tasks:
    - name: Print init
      debug:
        msg: Starting initialization of Access Worker node

    - name: Docker role
      debug:
        msg: Installing docker

    - import_role:
        name: docker
      tags: docker-installation

    - name: Worker role
      debug:
        msg: Setting up worker node

    - import_role:
        name: worker
      tags: worker
