---
- block:
    - name: Create docker.service.d folder
      file:
        path: /var/docker
        state: directory

    - name: Copy docker certs for server
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: 600
      with_items:
        - { src: 'host_files/{{ inventory_hostname }}/ca.pem', dest: '/var/docker/ca.pem' }
        - { src: 'host_files/{{ inventory_hostname }}/server-cert.pem', dest: '/var/docker/server-cert.pem' }
        - { src: 'host_files/{{ inventory_hostname }}/server-key.pem', dest: '/var/docker/server-key.pem' }

    - name: Copy docker daemon.json file
      template:
        src: ../files/docker-daemon-tls.json.j2
        dest: /etc/docker/daemon.json
        mode: 600

    - name: Create docker.service.d folder
      file:
        path: /etc/systemd/system/docker.service.d/
        state: directory

    - name: Override default docker service file to be usable with daemon.json
      copy:
        src: ../files/no_host_docker.service.d
        dest: /etc/systemd/system/docker.service.d/docker.conf
        mode: 600

    - name: Restart Docker service to apply changes
      shell: |
        systemctl daemon-reload
        systemctl restart docker.service
        systemctl enable docker
        netstat -tulnp | grep dockerd
      register: out
    - debug: var=out.stdout_lines

