#################################################
# DO Community Playbooks: Docker
#################################################
---
- block:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools', 'unzip']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install docker
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'docker-ce', 'docker-ce-cli', 'containerd.io' ]

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Pull default Docker image
      docker_image:
        name: hello-world
        source: pull

    - name: Test Docker installation with hello-world
      docker_container:
        name: helloWorld
        image: "hello-world:latest"

    - name: Install compose
      pip:
        name: docker-compose
        state: present

    - name: Copy daemon.json and service files
      copy:
        src: "docker-daemon.json"
        dest: "/etc/docker/daemon.json"
        mode: 600

    - name: Restart Docker service to apply changes
      systemd:
        name: docker
        state: restarted
        daemon_reload: yes
        enabled: yes

